version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: node-test-bluegreen
        LoadBalancerInfo:
          ContainerName: "node-test-container"
          ContainerPort: 80